import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "animate.css/animate.min.css";
import "bootstrap/dist/css/bootstrap.min.css";
import Script from "next/script";
import "../styles/globals.css";
import { NavBar } from "@/components/NavBar";
import { Footer } from "@/components/Footer";

/*
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

className={`${geistSans.variable} ${geistMono.variable} antialiased`}
*/

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
        <head>
          <link href="https://fonts.googleapis.com/css2?family=Lato:wght@300&display=swap" rel="stylesheet" />
        </head>
        <body>

          <NavBar />
          <main>
            {children}
          </main>
          

          <Footer />

          <Script
          src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js"
          strategy="afterInteractive"
          />

        </body>
      </html>
  );
}
